Repository domiK66/SportChimp, pull requests merged in 2022-01, with the labels that each got.

#25 fix user_id hack
  frontend/src/app/services/user.service.ts
Labels: Security

#27 fix date-placeholder bug
  frontend/src/app/date/date.component.ts
Labels: bug

#34 basic user profile
  frontend/src/app/profile/profile.component.html
  frontend/src/app/profile/profile.component.ts
Labels: Angular

#36 add basic Activity-Details View
  frontend/src/app/activity-details/activity-details.component.html
  frontend/src/app/activity-details/activity-details.component.scss
  frontend/src/app/activity-details/activity-details.component.spec.ts
  frontend/src/app/activity-details/activity-details.component.ts
  frontend/src/app/activity-list/activity-list.component.html
  frontend/src/app/activity-view/activity-view.component.html
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
Labels: Angular
